/** Canonical browse taxonomy from Figma charts — Icon最新稿 */

export const figmaTaxonomy = {
  actions: {
    transfer: ['download', 'upload', 'export', 'external-link', 'share', 'reply', 'send', 'cloud-download', 'cloud-upload'],
    editing: ['plus', 'minus', 'close', 'check', 'copy', 'paste', 'trash', 'cut', 'edit', 'undo', 'redo', 'save', 'paperclip', 'translate', 'marquee'],
    session: ['power', 'login', 'logout'],
    view: ['maximize-alt', 'minimize-alt', 'expand-collapse', 'maximize', 'minimize', 'zoom-in', 'zoom-out', 'scan', 'screenshot'],
    arrangement: ['set-top', 'set-medium', 'set-bottom'],
    'text-align': ['text-align-left', 'text-align-right', 'text-align-center', 'text-align-justify', 'text-align-justify-alt'],
    'object-align': ['object-align-left', 'object-align-center', 'object-align-right', 'object-align-justify', 'object-align-justify-alt'],
    management: ['smartphone', 'refresh', 'search', 'pin', 'pin-off', 'filter', 'sort', 'archive'],
  },
  navigation: {
    destination: ['home', 'compass', 'exit'],
    chevron: ['chevron-up', 'chevron-down', 'chevron-left', 'chevron-right'],
    chevrons: ['chevrons-up', 'chevrons-down', 'chevrons-left', 'chevrons-right'],
    arrow: ['arrow-up', 'arrow-down', 'arrow-left', 'arrow-right', 'arrow-top-left', 'arrow-top-right', 'arrow-bottom-left', 'arrow-bottom-right'],
  },
  interface: {
    controls: ['setting', 'setting-alt', 'control-horizon', 'control-vertical', 'checkbox', 'toggle', 'radio', 'tabs', 'battery-vertical', 'calculator'],
    appearance: ['eye', 'eye-off', 'sun', 'moon', 'clarity', 'color', 'color-wheel'],
    design: [
      'text', 'underline', 'text-alt', 'strikethrough', 'bold', 'italic', 'heading', 'quote', 'code-block', 'artboard',
      'pen', 'pencil', 'ruler', 'eyedropper', 'anchor-curve', 'anchor-point', 'crop',
      'rotate-left', 'rotate-right', 'flip-horizontal', 'flip-vertical',
      'duplicate', 'transform', 'union', 'intersect', 'exclude', 'subtract', 'mask', 'eraser', 'textarea',
    ],
    interaction: ['mouse', 'mouse-alt', 'monitor', 'touchpad', 'keyboard', 'hand', 'cursor', 'target', 'target-alt', 'drag-alt', 'drag'],
    data: ['pie-chart', 'chart-column', 'chart-column-up', 'gauge', 'dial', 'trending-up', 'trending-down', 'percent'],
    structure: [
      'sidebar-left', 'sidebar-right', 'panel-left', 'panel-right', 'layers', 'list', 'list-ordered', 'table',
      'separator', 'split-screen', 'grid', 'grid-alt', 'masonry', 'masonry-alt', 'visualization',
    ],
    menu: ['menu', 'more-horizon', 'more-vertical'],
  },
  media: {
    playback: ['play', 'stop', 'pause', 'skip-forward', 'skip-back', 'fast-forward', 'rewind', 'repeat', 'shuffle', 'record', 'cast'],
    audio: ['microphone', 'volume-up', 'volume-down', 'volume-high', 'volume-low', 'volume-off', 'volume', 'waveform', 'music'],
    visual: ['camera', 'video', 'image'],
    gaming: ['game-handle'],
  },
  objects: {
    content: ['file', 'folder', 'folder-open', 'folder-plus', 'clipboard', 'task', 'braces', 'book', 'hashtag', 'bookmark', 'tag', 'mail', 'notebook'],
    communication: ['info', 'comment', 'inbox', 'megaphone', 'bell', 'bell-off', 'phone', 'headset', 'link', 'at-sign', 'link-off', 'url'],
    technology: [
      'tablet', 'laptop', 'computer', 'robot', 'print', 'server', 'qr-code', 'barcode', 'battery-horizon', 'chip', 'cube',
      'database', 'charge', 'git', 'floppy-disk', 'hard-drive', 'terminal', 'bug', 'wifi', 'wifi-off', 'bluetooth',
      'bluetooth-off', 'cloud', 'broadcast', 'vr',
    ],
    time: ['clock', 'alarm-clock', 'timer', 'calendar'],
    place: ['location', 'earth', 'global', 'planet', 'skyscraper', 'flag', 'map', 'mountain'],
    identity: ['user', 'users', 'gender-male', 'gender-transgender', 'gender-neutral', 'gender-female'],
    commerce: [
      'store', 'wallet', 'shopping-cart', 'shopping-bag', 'card', 'gift', 'credit-card', 'coupon', 'receipt',
      'currency', 'currency-yuan', 'currency-yen', 'currency-euro', 'currency-dollar', 'subscription', 'ticket', 'ticket-alt',
    ],
    security: ['key', 'fingerprint'],
    mineral: ['diamond'],
    life: ['cup', 'lamp', 'flashlight', 'glasses', 'lightbulb', 'pet', 'leaf'],
    sport: ['basketball', 'football'],
    professional: ['student', 'lab', 'briefcase'],
    mobility: ['ship-rudder', 'truck', 'jeep', 'plane', 'rocket', 'space-shuttle'],
  },
  status: {
    feedback: ['heart', 'star', 'thumbs-up', 'thumbs-down', 'smile', 'uninteresting'],
    security: ['unlock', 'lock', 'shield', 'unsafe', 'shield-check'],
    alter: ['warning', 'danger', 'help', 'mistake', 'success'],
    system: ['activity', 'flash', 'hourglass', 'transfer', 'sync', 'loading'],
    achievement: ['laurel', 'badge', 'trophy', 'sparkle'],
  },
}

export const subgroupLabels = {
  transfer: ['Transfer', '传输'],
  editing: ['Editing', '编辑'],
  session: ['Session', '会话'],
  view: ['View', '视图'],
  arrangement: ['Arrangement', '排列'],
  'object-align': ['Object align', '对象对齐'],
  'text-align': ['Text align', '文本对齐'],
  management: ['Management', '管理'],
  destination: ['Destination', '目的地'],
  chevron: ['Chevron', '单折线'],
  chevrons: ['Chevrons', '双折线'],
  arrow: ['Arrow', '箭头'],
  controls: ['Controls', '控件'],
  appearance: ['Appearance', '外观'],
  design: ['Design', '设计'],
  interaction: ['Interaction', '交互'],
  data: ['Data', '数据'],
  structure: ['Structure', '结构'],
  menu: ['Menu', '菜单'],
  playback: ['Playback', '播放'],
  audio: ['Audio', '音频'],
  visual: ['Visual', '视觉'],
  gaming: ['Gaming', '游戏'],
  content: ['Content', '内容'],
  communication: ['Communication', '沟通'],
  technology: ['Technology', '技术'],
  time: ['Time', '时间'],
  place: ['Place', '地点'],
  identity: ['Identity', '身份'],
  commerce: ['Commerce', '商务'],
  security: ['Security', '安全'],
  mineral: ['Mineral', '矿物'],
  life: ['Life', '生活'],
  sport: ['Sport', '运动'],
  professional: ['Professional', '职业'],
  mobility: ['Mobility', '出行'],
  feedback: ['Feedback', '反馈'],
  alter: ['Alert', '警示'],
  system: ['System', '系统'],
  achievement: ['Achievement', '成就'],
}

export const categoryRegistry = [
  { id: 'actions', title: 'Actions', titleZh: '操作', description: 'Commands, editing, transfer, and view controls' },
  { id: 'navigation', title: 'Navigation', titleZh: '导航', description: 'Direction, movement, and wayfinding' },
  { id: 'interface', title: 'Interface', titleZh: '界面', description: 'Controls, structure, creation, and interface tooling' },
  { id: 'media', title: 'Media', titleZh: '媒体', description: 'Playback, audio, visual capture, and gaming' },
  { id: 'objects', title: 'Objects', titleZh: '对象', description: 'Files, devices, places, commerce, and tangible concepts' },
  { id: 'status', title: 'Status', titleZh: '状态', description: 'Feedback, security, alerts, and system state' },
]
