export * from './generated/components.js'
export { createIcon } from './createIcon.js'
export { IconBase } from './IconBase.js'
export type { IconName } from '@uplus-icon/core'
export type { IconBaseProps } from './types.js'
export type { UplusIcon } from './createIcon.js'
