import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises'
import { basename, dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const rawDir = join(root, 'raw')
const outputDir = join(root, 'src', 'generated')
const toPascal = (name) => name.split('-').map((part) => part[0].toUpperCase() + part.slice(1)).join('')

await mkdir(outputDir, { recursive: true })
const files = (await readdir(rawDir)).filter((file) => file.endsWith('.svg')).sort()
const icons = []

for (const file of files) {
  const name = basename(file, '.svg')
  let svg = await readFile(join(rawDir, file), 'utf8')
  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1] ?? '0 0 24 24'
  const idPrefix = `uplus-${name}-`
  const body = svg
    .replace(/^<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace(/\sclip-path="url\(#[^)]+\)"/g, '')
    .replace(/<defs>[\s\S]*?<\/defs>/g, '')
    .replaceAll('fill="black"', 'fill="currentColor"')
    .replaceAll('stroke="black"', 'stroke="currentColor"')
    .replaceAll('fill="white"', 'fill="currentColor"')
    .replace(/id="([^"]+)"/g, `id="${idPrefix}$1"`)
    .replace(/url\(#([^)]*)\)/g, `url(#${idPrefix}$1)`)
    .replace(/(?:href|xlink:href)="#([^"]+)"/g, (match, id) => match.replace(`#${id}`, `#${idPrefix}${id}`))
    .replace(/\s(?:width|height)="[^"]*"/g, '')
  icons.push({ name, component: `${toPascal(name)}Icon`, viewBox, body })
}

const source = `// Generated by scripts/generate.mjs. Do not edit directly.\nexport const iconData = ${JSON.stringify(icons, null, 2)} as const\n\nexport type IconName = typeof iconData[number]['name']\n`
await writeFile(join(outputDir, 'icons.ts'), source)
const components = `// Generated by scripts/generate.mjs. Do not edit directly.\nimport { createIcon } from '../createIcon'\n${icons.map(({ name, component }) => `export const ${component} = createIcon('${name}')`).join('\n')}\n`
await writeFile(join(outputDir, 'components.ts'), components)
console.log(`Generated ${icons.length} icons`)
