// Generated by scripts/generate.mjs. Do not edit directly.
import { createIcon } from '../createIcon.js'

const icon = {
  "name": "arrow-down",
  "viewBox": "0 0 24 24",
  "body": "\n<path d=\"M13.414 20.4143C12.633 21.1952 11.3669 21.1952 10.5859 20.4143L5.29285 15.1213C4.90247 14.7308 4.90237 14.0977 5.29285 13.7073C5.68333 13.3169 6.31641 13.3169 6.70692 13.7073L10.9999 18.0002V3.41429C11.0001 2.86213 11.4478 2.41433 11.9999 2.41429C12.5521 2.41429 12.9998 2.86211 12.9999 3.41429V18.0002L17.2929 13.7073C17.6834 13.3169 18.3165 13.3169 18.707 13.7073C19.0975 14.0978 19.0975 14.7308 18.707 15.1213L13.414 20.4143Z\" fill=\"black\"/>\n"
}

export const ArrowDownIcon = createIcon(icon)
export default ArrowDownIcon
