// Generated by scripts/generate.mjs. Do not edit directly.
import { createIcon } from '../createIcon.js'

const icon = {
  "name": "arrow-left",
  "viewBox": "0 0 24 24",
  "body": "\n<path d=\"M3.29286 13.1212C2.51192 12.3401 2.51192 11.0741 3.29286 10.293L8.58583 5C8.97637 4.60963 9.60942 4.60953 9.9999 5C10.3903 5.39049 10.3902 6.02356 9.9999 6.41408L5.70693 10.7071H20.2929C20.845 10.7072 21.2928 11.1549 21.2929 11.7071C21.2929 12.2593 20.845 12.707 20.2929 12.7071H5.70693L9.9999 17.0001C10.3903 17.3906 10.3902 18.0237 9.9999 18.4142C9.6094 18.8047 8.97636 18.8046 8.58583 18.4142L3.29286 13.1212Z\" fill=\"black\"/>\n"
}

export const ArrowLeftIcon = createIcon(icon)
export default ArrowLeftIcon
