// Generated by scripts/generate.mjs. Do not edit directly.
import { createIcon } from '../createIcon.js'

const icon = {
  "name": "arrow-right",
  "viewBox": "0 0 24 24",
  "body": "\n<path d=\"M20.7071 10.2931C21.4881 11.0742 21.4881 12.3403 20.7071 13.1213L15.4142 18.4143C15.0236 18.8047 14.3906 18.8048 14.0001 18.4143C13.6097 18.0238 13.6098 17.3907 14.0001 17.0002L18.2931 12.7072H3.70714C3.15498 12.7071 2.70718 12.2594 2.70714 11.7072C2.70714 11.155 3.15495 10.7073 3.70714 10.7072H18.2931L14.0001 6.41421C13.6097 6.02372 13.6098 5.39065 14.0001 5.00013C14.3906 4.60963 15.0236 4.60968 15.4142 5.00013L20.7071 10.2931Z\" fill=\"black\"/>\n"
}

export const ArrowRightIcon = createIcon(icon)
export default ArrowRightIcon
