// Generated by scripts/generate.mjs. Do not edit directly.
import { createIcon } from '../createIcon.js'

const icon = {
  "name": "caret-down",
  "viewBox": "0 0 24 24",
  "body": "\n<path d=\"M3.29302 7.29289C2.90249 7.68342 2.90249 8.31643 3.29302 8.70696L9.87895 15.2929C11.0505 16.4643 12.9496 16.4643 14.1211 15.2929L20.7071 8.70696C21.0976 8.31643 21.0976 7.68342 20.7071 7.29289C20.3166 6.90237 19.6835 6.90237 19.293 7.29289L12.7071 13.8788C12.3166 14.2692 11.6835 14.2692 11.293 13.8788L4.70708 7.29289C4.31655 6.90237 3.68354 6.90237 3.29302 7.29289Z\" fill=\"black\"/>\n"
}

export const CaretDownIcon = createIcon(icon)
export default CaretDownIcon
