// Generated by scripts/generate.mjs. Do not edit directly.
import { createIcon } from '../createIcon.js'

const icon = {
  "name": "caret-up",
  "viewBox": "0 0 24 24",
  "body": "\n<path d=\"M3.29302 16.7071C2.90249 16.3166 2.90249 15.6836 3.29302 15.293L9.87895 8.70711C11.0505 7.53573 12.9496 7.53574 14.1211 8.70711L20.7071 15.293C21.0976 15.6836 21.0976 16.3166 20.7071 16.7071C20.3166 17.0976 19.6835 17.0976 19.293 16.7071L12.7071 10.1212C12.3166 9.73084 11.6835 9.73085 11.293 10.1212L4.70708 16.7071C4.31655 17.0976 3.68354 17.0976 3.29302 16.7071Z\" fill=\"black\"/>\n"
}

export const CaretUpIcon = createIcon(icon)
export default CaretUpIcon
