// Generated by scripts/generate.mjs. Do not edit directly.
import { createIcon } from '../createIcon.js'

const icon = {
  "name": "check",
  "viewBox": "0 0 24 24",
  "body": "\n<path d=\"M18.2569 6.33096C18.6264 5.9205 19.2585 5.8873 19.669 6.25674C20.0795 6.62621 20.1127 7.25836 19.7432 7.66885L12.335 15.9003C11.0887 17.285 8.89509 17.2107 7.74517 15.745L4.21294 11.2421C3.87219 10.8075 3.94833 10.1786 4.38286 9.83779C4.81743 9.49704 5.44635 9.57318 5.78716 10.0077L9.31841 14.5106C9.70172 14.9992 10.4332 15.024 10.8487 14.5624L18.2569 6.33096Z\" fill=\"black\"/>\n"
}

export const CheckIcon = createIcon(icon)
export default CheckIcon
