// Generated by scripts/generate.mjs. Do not edit directly.
import { createIcon } from '../createIcon.js'

const icon = {
  "name": "columns",
  "viewBox": "0 0 24 24",
  "body": "\n<path d=\"M18 4C20.2091 4 22 5.79086 22 8V16C22 18.2091 20.2091 20 18 20H6C3.79086 20 2 18.2091 2 16V8C2 5.79086 3.79086 4 6 4H18ZM9 18H18C19.1046 18 20 17.1046 20 16V8C20 6.89543 19.1046 6 18 6H9V18ZM6 6C4.89543 6 4 6.89543 4 8V16C4 17.1046 4.89543 18 6 18H7V6H6Z\" fill=\"black\"/>\n"
}

export const ColumnsIcon = createIcon(icon)
export default ColumnsIcon
