// Generated by scripts/generate.mjs. Do not edit directly.
import { createIcon } from '../createIcon.js'

const icon = {
  "name": "copy",
  "viewBox": "0 0 24 24",
  "body": "\n<path d=\"M18 2C19.6569 2 21 3.34315 21 5V16C21 17.6569 19.6569 19 18 19H17C17 20.6569 15.6569 22 14 22H6C4.34315 22 3 20.6569 3 19V8C3 6.34315 4.34315 5 6 5H7C7 3.34315 8.34315 2 10 2H18ZM6 7C5.44772 7 5 7.44772 5 8V19C5 19.5523 5.44772 20 6 20H14C14.5523 20 15 19.5523 15 19V8C15 7.44772 14.5523 7 14 7H6ZM14 5C15.6569 5 17 6.34315 17 8V17H18C18.5523 17 19 16.5523 19 16V5C19 4.44772 18.5523 4 18 4H10C9.44772 4 9 4.44772 9 5H14Z\" fill=\"black\"/>\n"
}

export const CopyIcon = createIcon(icon)
export default CopyIcon
