// Generated by scripts/generate.mjs. Do not edit directly.
import { createIcon } from '../createIcon.js'

const icon = {
  "name": "minus",
  "viewBox": "0 0 24 24",
  "body": "\n<path d=\"M20 11C20.5523 11 21 11.4477 21 12C21 12.5523 20.5523 13 20 13H4C3.44772 13 3 12.5523 3 12C3 11.4477 3.44772 11 4 11H20Z\" fill=\"black\"/>\n"
}

export const MinusIcon = createIcon(icon)
export default MinusIcon
