// Generated by scripts/generate.mjs. Do not edit directly.
import { createIcon } from '../createIcon.js'

const icon = {
  "name": "play",
  "viewBox": "0 0 24 24",
  "body": "\n<path d=\"M3.5 5.72362C3.5 3.49211 5.83556 2.06634 7.7998 3.01854L7.98828 3.11815L18.9727 9.39549C20.9881 10.5472 20.9881 13.4528 18.9727 14.6045L7.98828 20.8818C5.98835 22.0244 3.5 20.5797 3.5 18.2764V5.72362ZM5.5 18.2764C5.5 18.9961 6.22873 19.4641 6.86914 19.206L6.99609 19.1455L17.9805 12.8681C18.6104 12.5082 18.6499 11.634 18.0986 11.2099L17.9805 11.1318L6.99609 4.85448C6.32948 4.47377 5.5 4.95588 5.5 5.72362V18.2764Z\" fill=\"black\"/>\n"
}

export const PlayIcon = createIcon(icon)
export default PlayIcon
