// Generated by scripts/generate.mjs. Do not edit directly.
import { createIcon } from '../createIcon.js'

const icon = {
  "name": "search",
  "viewBox": "0 0 24 24",
  "body": "\n<g clip-path=\"url(#clip0_2344_3442)\">\n<path d=\"M4.24267 4.24256C7.36686 1.11837 12.4322 1.11837 15.5564 4.24256C18.441 7.12721 18.6602 11.6652 16.2179 14.8036L19.2929 17.8785C19.6834 18.2691 19.6834 18.9022 19.2929 19.2927C18.9023 19.6832 18.2691 19.6832 17.8786 19.2927L14.8037 16.2178C11.6653 18.6601 7.12732 18.4409 4.24267 15.5563C1.11848 12.4321 1.11848 7.36675 4.24267 4.24256ZM5.65688 5.65677C3.31374 7.99992 3.31374 11.7989 5.65688 14.1421C8.00003 16.4852 11.799 16.4852 14.1422 14.1421C16.4853 11.7989 16.4853 7.99992 14.1422 5.65677C11.799 3.31363 8.00003 3.31363 5.65688 5.65677Z\" fill=\"black\"/>\n</g>\n<defs>\n<clipPath id=\"clip0_2344_3442\">\n<rect width=\"24\" height=\"24\" fill=\"white\"/>\n</clipPath>\n</defs>\n"
}

export const SearchIcon = createIcon(icon)
export default SearchIcon
