// Generated by scripts/generate.mjs. Do not edit directly.
import { createIcon } from '../createIcon.js'

const icon = {
  "name": "separator",
  "viewBox": "0 0 24 24",
  "body": "\n<path d=\"M13.3633 3.04796C13.5062 2.51449 14.0545 2.19791 14.588 2.34085V2.34085C15.1215 2.48379 15.438 3.03213 15.2951 3.5656L10.6364 20.9523C10.4934 21.4857 9.94508 21.8023 9.41161 21.6594V21.6594C8.87815 21.5164 8.56157 20.9681 8.70451 20.4346L13.3633 3.04796Z\" fill=\"black\"/>\n"
}

export const SeparatorIcon = createIcon(icon)
export default SeparatorIcon
